### ISSUE TITLE
TypeError in Leaflet 0.6.2 after distance layer added with MeasuringTool

### ISSUE THREAD

**Issue by arthur-e** [kartena/Leaflet.EditableHandlers#5]
I modified the packaged example, `measuring-tool.html`, to use Leaflet 0.6.2 instead of the packaged version. This results in a TypeError when completing a distance measurement, after the PopUp appears.

```
Uncaught TypeError: Object [object Object] has no method 'fire' leaflet-src.js:3809
L.Popup.L.Class.extend.onAdd leaflet-src.js:3809
L.Map.L.Class.extend._layerAdd leaflet-src.js:2246
L.Map.L.Class.extend.addLayer leaflet-src.js:1714
L.MeasuringTool.L.Class.extend._onMapClick L.MeasuringTool.js:94
L.Mixin.Events.fireEvent leaflet-src.js:473
L.Map.L.Class.extend._fireMouseEvent leaflet-src.js:2215
L.Map.L.Class.extend._onMouseClick leaflet-src.js:2194
handler
```

This is a nice library, and I'd like to use it with 0.6.2 (or later)!

**Comment by arthur-e** [comment]
A quick-and-dirty fix seems to be inserting the following line above the current Line 94 of `L.MeasuringTool.js`, above the line `this._map.addLayer(this._distancePopup)...`:

```
this._distancePopup._source = this._measureLine;
```

I'm not saying this is the best fix, if even the intent is to provide support for 0.6.2+. I'm still trying to track down what changed before this version that might have broken this feature.

**Comment by keyjote** [comment]
this has been fixed
