### ISSUE TITLE
L.CircleEditor  '_leaflet_id' undefined error with leaflet master branch (0.8-dev)

### ISSUE THREAD

**Issue by dinglixiang** [kartena/Leaflet.EditableHandlers#7]
Hi there

We've recently had to upgrade to the latest Leaflet master branch due to better Mapbox support, among other reasons. Leaflet master seems to have had many internal changes and has caused L.CircleEditor to throw an error:

```
Uncaught TypeError: Cannot read property '_leaflet_id' of undefined 
L.Util.stamp leaflet-0-8-dev.js:81
L.Evented.L.Class.extend._on leaflet-0-8-dev.js:399
```

Here's a jsfiddle on it: http://jsfiddle.net/dinglixiang/sXh5k/24/

It's pointing to the latest build of Leaflet master branch at our server.

Could you kindly take a look and advise on what the issue might be? Much thanks.

**Comment by xnzacc** [comment]
I'm dinglixiang's colleague. We're still trying to resolve this issue. Any help on this would be greatly appreciated, even if it's just pointing us at the right direction.

**Comment by keyjote** [comment]
hi, sorry, for the delay. I have done some changes for this library and I have just deployed it. Looking at your example, it seems that this issue has been fixed. Also, the problem is not in the L.CircleEditor but in the leaflet library itself.
Have you found out anything else regarding this problem?

**Comment by xnzacc** [comment]
Np, thanks for the reply.

The commenting out of the event handling code fixed it for us. Haven't had any other issues!

**Comment by keyjote** [comment]
good to hear :)
